# Generated by Django 5.2.4 on 2025-12-15 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20250724_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='fecha_visita',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='foto_comentario',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrovisita',
            name='hora_entrada',
            field=models.TimeField(auto_now=True),
        ),
    ]
